// Generated by CoffeeScript 1.7.1
(function() {
  var SleepBeforeOnCompile, q;

  q = require('q');

  module.exports = SleepBeforeOnCompile = (function() {
    SleepBeforeOnCompile.prototype.brunchPlugin = true;

    function SleepBeforeOnCompile(config) {
      var _ref;
      this.config = config;
      this.sleepMillis = (_ref = this.config.plugins.sleepBeforeOnCompile) != null ? _ref : 0;
    }

    SleepBeforeOnCompile.prototype.onCompile = function(generatedFiles) {
      var deferred, noopFn1, noopFn2;
      deferred = q.defer();
      noopFn1 = function() {
        return deferred.resolve();
      };
      noopFn2 = function() {};
      setTimeout(noopFn1, this.sleepMillis);
      deferred.then(noopFn2);
    };

    return SleepBeforeOnCompile;

  })();

}).call(this);
